export * from "./addToDom";
// export * from "./isValidYearFormat";
// export * from "./modalUtils";
// export * from "./insertBefore";
// export * from "./removeFromDom";
export * from "./showErrMsg";
export * from "./validateNamefield";
export * from "./validatePhonefield";
export * from "./validateSelectfield";
export * from "./validateDate";
//export * from "./studentFormUtils";
export * from "./validateAddress";
//export * from "./addToTabMenuHelper";
export * from "./notifyToast";
export * from "./staticValues";
